# Starter pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: DockerInstaller@0
  displayName: Installing Docker 17
  inputs:
    dockerVersion: '17.09.0-ce'    
    
- task: Docker@2
  inputs:
    containerRegistry: 'mgsuraj-dockerhub'
    repository: 'mgsuraj/k8s-repository'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: KubernetesManifest@1
  displayName: Deploying on GKE K8s
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'svc-k8s-cluster'
    namespace: 'default'
    manifests: |
      k8s/deployment.yaml
      k8s/service.yaml